language: elixir
elixir:
  - 1.10.3
otp_release:
  - 22.1.8
services:
  - postgresql
cache:
  directories:
  - _build
  - deps
script:
  - mix do setup, compile --warnings-as-errors, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test
cache:
  directories:
  - _build
  - deps
